services:
  minion:
    image: opennms/minion:33.0.2
    container_name: hamhung-minion
    hostname: hamhung-minion
    environment:
      MINION_ID: hamhung-minion-01
      MINION_LOCATION: Hamhung
      OPENNMS_HTTP_URL: http://marr-horizon:8980/opennms
      OPENNMS_HTTP_USER: admin
      OPENNMS_HTTP_PASS: admin
      OPENNMS_BROKER_URL: tcp://marr-activemq:61616
    command: ["-c"]
    entrypoint: ["/opt/minion-startup.sh"]
    volumes:
      - hamhung-minion-data:/opt/minion-data
      - ./minion-startup.sh:/opt/minion-startup.sh:ro
      - ./opennms.properties.d:/opt/minion/etc/opennms.properties.d:ro
    networks:
      marr-net:
        ipv4_address: 172.21.0.20
volumes:
  hamhung-minion-data:
networks:
  marr-net:
    external: true
# Author: Jose Batalha De Vasconcelos - COM617 Group 15
