frr version 8.4_git
frr defaults traditional
hostname hamhung-router
log syslog informational
no ipv6 forwarding
!
ip route 192.168.11.0/24 Null0
!
interface eth1
 ip address 10.0.14.2/30
exit
!
router bgp 65004
 bgp router-id 10.0.14.2
 no bgp ebgp-requires-policy
 neighbor 10.0.14.1 remote-as 65001
 !
 address-family ipv4 unicast
  network 192.168.11.0/24
 exit-address-family
exit
!
