frr version 8.4.1
frr defaults traditional
hostname router1
log syslog informational
log facility local7
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.12.1/30
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20
!
interface eth2
 ip address 10.0.13.1/30
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20
!
interface lo
 ip address 10.255.0.1/32
 ip ospf area 0
!
router ospf
 ospf router-id 10.255.0.1
 network 10.0.0.0/8 area 0
 passive-interface lo
!
router bgp 65001
 bgp router-id 10.255.0.1
 bgp log-neighbor-changes
 !
 neighbor 10.0.12.2 remote-as 65002
 neighbor 10.0.12.2 description router2
 neighbor 10.0.12.2 bfd
 neighbor 10.0.12.2 timers 10 30
 !
 neighbor 10.0.13.2 remote-as 65003
 neighbor 10.0.13.2 description router3
 neighbor 10.0.13.2 bfd
 neighbor 10.0.13.2 timers 10 30
 !
 address-family ipv4 unicast
  network 10.255.0.1/32
 exit-address-family
!
line vty
!
