frr version 9.1.0
frr defaults traditional
hostname router3
log syslog informational
log facility local7
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.13.2/30
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20
!
interface eth2
 ip address 10.0.23.2/30
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20
!
interface lo
 ip address 10.255.0.3/32
 ip ospf area 0
!
router ospf
 ospf router-id 10.255.0.3
 network 10.0.0.0/8 area 0
 passive-interface lo
!
router bgp 65003
 bgp router-id 10.255.0.3
 bgp log-neighbor-changes
 !
 neighbor 10.0.13.1 remote-as 65001
 neighbor 10.0.13.1 description router1
 neighbor 10.0.13.1 bfd
 neighbor 10.0.13.1 timers 10 30
 !
 neighbor 10.0.23.1 remote-as 65002
 neighbor 10.0.23.1 description router2
 neighbor 10.0.23.1 bfd
 neighbor 10.0.23.1 timers 10 30
 !
 address-family ipv4 unicast
  network 10.255.0.3/32
 exit-address-family
!
line vty
!
